import Foundation

/// One pasteboard item: every type it carries, in the order the pasteboard listed them, with its data.
public struct PasteboardItemData: Equatable, Sendable {
    public var entries: [(type: String, data: Data)]

    public init(_ entries: [(type: String, data: Data)]) { self.entries = entries }

    public var types: [String] { entries.map { $0.type } }

    public static func == (a: Self, b: Self) -> Bool {
        a.entries.count == b.entries.count && zip(a.entries, b.entries).allSatisfy { $0.type == $1.type && $0.data == $1.data }
    }
}

/// The few pasteboard calls the reconcile needs, so it tests against a fake and runs against
/// `NSPasteboard` (`GeneralPasteboard` in CaretHost).
public protocol PasteboardBackend: AnyObject {
    var changeCount: Int { get }
    /// Every item, every type.
    func read() -> [PasteboardItemData]
    /// Clears the pasteboard and writes `items` (none leaves it empty). Returns the change count
    /// the clear produced, which a write by anyone else between the caller's check and this call
    /// would have moved past `expected + 1`.
    func replace(with items: [PasteboardItemData]) -> Int
}

/// Insertion through the general pasteboard, by Sam's decision of 2026-10-04: paste, then reconcile.
///
/// 1. `save` copies every item and type on the pasteboard, and its change count.
/// 2. `writeOwn` writes Caret's text marked with the nspasteboard.org transient, concealed and
///    auto-generated types, so clipboard managers skip it, and records the change count that write
///    produced: from then on, that count means "still Caret's".
/// 3. `restore`, once the paste has landed, puts the saved items back only if the count is still
///    Caret's. Any other count means someone wrote in between (the user copied), and their copy
///    stays. An empty saved pasteboard is restored as empty.
///
/// NSPasteboard has no compare-and-swap, so a copy made in the instant between the count check and
/// the clear is overwritten. The clear's own count shows that it happened (`Outcome.raced`), and
/// the debug state reports it; nothing can bring that copy back.
public final class ReconcilingClipboard {
    public enum Outcome: String, Codable, Equatable, Sendable {
        /// The saved contents are back.
        case restored
        /// Someone wrote after Caret did; their contents stay and Caret's saved copy is dropped.
        case skippedUserCopied
        /// The check passed but another write landed before the clear: it was overwritten.
        case raced
        /// Nothing was written by Caret, so there was nothing to put back.
        case notWritten
    }

    /// nspasteboard.org's markers. A clipboard manager that honours them does not record the item.
    public static let markerTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    public static let plainText = "public.utf8-plain-text"

    private let backend: PasteboardBackend
    private var saved: [PasteboardItemData]?
    /// The change count Caret's own write produced.
    public private(set) var ownCount: Int?

    public init(backend: PasteboardBackend) { self.backend = backend }

    public func save() {
        saved = backend.read()
        ownCount = nil
    }

    /// Writes `text` as Caret's own item. Returns the change count it produced.
    @discardableResult
    public func writeOwn(_ text: String) -> Int {
        var entries: [(type: String, data: Data)] = [(Self.plainText, Data(text.utf8))]
        for marker in Self.markerTypes { entries.append((marker, Data())) }
        _ = backend.replace(with: [PasteboardItemData(entries)])
        // Read after the write, not taken from the clear: whether writing items moves the count
        // too is AppKit's business (GeneralPasteboardTests pins what it does today).
        let count = backend.changeCount
        ownCount = count
        return count
    }

    /// Puts the saved contents back if the pasteboard still holds Caret's write.
    public func restore() -> Outcome {
        defer {
            saved = nil
            ownCount = nil
        }
        guard let own = ownCount, let saved else { return .notWritten }
        guard backend.changeCount == own else { return .skippedUserCopied }
        let cleared = backend.replace(with: saved)
        return cleared == own + 1 ? .restored : .raced
    }
}
