import Foundation

/// One pasteboard item: every type it carries, in the order the pasteboard listed them, with its data.
public struct PasteboardItemData: Equatable, Sendable {
    public var entries: [(type: String, data: Data)]
    /// Types the pasteboard listed for the item whose data could not be read, so a restore cannot
    /// bring them back. Reported, never guessed at.
    public var unreadable: [String]

    public init(_ entries: [(type: String, data: Data)], unreadable: [String] = []) {
        self.entries = entries
        self.unreadable = unreadable
    }

    public var types: [String] { entries.map { $0.type } }

    public static func == (a: Self, b: Self) -> Bool {
        a.unreadable == b.unreadable && a.entries.count == b.entries.count && zip(a.entries, b.entries).allSatisfy { $0.type == $1.type && $0.data == $1.data }
    }
}

/// The few pasteboard calls the reconcile needs, so it tests against a fake and runs against
/// `NSPasteboard` (`GeneralPasteboard` in CaretHost).
public protocol PasteboardBackend: AnyObject {
    var changeCount: Int { get }
    /// Every item, every type.
    func read() -> [PasteboardItemData]
    /// Clears the pasteboard and writes `items` (none leaves it empty). Returns the change count
    /// the clear produced, which a write by anyone else between the caller's check and this call
    /// would have moved past `expected + 1`.
    func replace(with items: [PasteboardItemData]) -> Int
}

/// Insertion through the general pasteboard, by Sam's decision of 2026-10-04: paste, then reconcile.
///
/// 1. `save` copies every item and type on the pasteboard, and its change count.
/// 2. `writeOwn` writes Caret's text marked with the nspasteboard.org transient, concealed and
///    auto-generated types, so clipboard managers skip it, and records the change count that write
///    produced: from then on, that count means "still Caret's".
/// 3. `restore`, once the paste has landed, puts the saved items back only if the count is still
///    Caret's. Any other count means someone wrote in between (the user copied), and their copy
///    stays. An empty saved pasteboard is restored as empty. A restore reads the pasteboard back
///    and reports every entry whose bytes differ (`mismatched`).
///
/// Known limit: NSPasteboard has no compare-and-swap, so a copy made in the instant between the
/// restore's count check and its clear (two adjacent calls on one thread) is overwritten. The clear's
/// own count shows that it happened (`Outcome.raced`), and the debug state reports it; nothing can
/// bring that copy back. Closing it would take not restoring at all.
public final class ReconcilingClipboard {
    public enum Outcome: String, Codable, Equatable, Sendable {
        /// The saved contents are back.
        case restored
        /// Someone wrote after Caret did; their contents stay and Caret's saved copy is dropped.
        case skippedUserCopied
        /// The check passed but another write landed before the clear: it was overwritten.
        case raced
        /// Nothing was written by Caret, so there was nothing to put back.
        case notWritten
    }

    /// nspasteboard.org's markers. A clipboard manager that honours them does not record the item.
    public static let markerTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    public static let plainText = "public.utf8-plain-text"

    /// Types that name a file instead of carrying bytes, and file promises (an app's offer to write
    /// a file later). A17's VM probe (vm-insert run 1, clipboard/pasteboard.ndjson) put back an
    /// item holding `public.file-url` 5 of 5 times, reported `restored` with nothing unreadable,
    /// and the item was gone each time.
    public static let fileTypes: Set<String> = [
        "public.file-url", "NSFilenamesPboardType",
        "com.apple.NSFilePromiseItemMetaData", "Apple files promise pasteboard type", "NSPromiseContentsPboardType",
    ]

    /// Whether this entry names a file or promises one: a type in `fileTypes`, any
    /// `com.apple.pasteboard.promised-` type, or a URL type whose data holds a file URL.
    public static func refersToFile(type: String, data: Data) -> Bool {
        if fileTypes.contains(type) || type.hasPrefix("com.apple.pasteboard.promised-") { return true }
        guard type == "public.url" || type == "Apple URL pasteboard type" else { return false }
        return data.range(of: Data("file:".utf8)) != nil
    }

    /// What in `items` refuses the paste route, item by item ("item 2: public.file-url"): types the
    /// pasteboard listed but gave no data for, and entries that name or promise a file. Empty when
    /// the paste route may be used.
    ///
    /// Every other type is saved and put back byte for byte, private types included (lead decision
    /// after A17, H5): its private type came back byte for byte. `restore` reads the pasteboard
    /// back and reports any entry that differs (`mismatched`). Until H5 every type outside a list of
    /// text, rich text, HTML and image types refused the paste.
    ///
    /// An item with no type Caret could read refuses too: `replace` writes back only what it read,
    /// so such an item would be dropped while the restore reported `restored`. V1b's VM run pasted
    /// over a clipboard whose second item held only `public.file-url` and lost that item; the saved
    /// evidence does not show what Caret's own read of it was (`DebugState.Insertion.clipboardTypes`
    /// now records it).
    public static func unrestorable(_ items: [PasteboardItemData]) -> [String] {
        items.enumerated().flatMap { i, item in
            let unreadable = item.entries.isEmpty && item.unreadable.isEmpty ? ["no readable type"] : item.unreadable
            return (unreadable + item.entries.filter { refersToFile(type: $0.type, data: $0.data) }.map(\.type)).map { "item \(i + 1): \($0)" }
        }
    }



    /// Where `now` differs from `saved`, entry by entry ("item 1: com.example.private: 4 bytes came
    /// back as 0", "item 2: missing"). Empty when every type of every item came back with its bytes.
    public static func mismatches(saved: [PasteboardItemData], now: [PasteboardItemData]) -> [String] {
        // An item with no readable entry is not written back (`PasteboardBackend.replace`).
        let expected = saved.filter { !$0.entries.isEmpty }
        var out: [String] = []
        for (i, item) in expected.enumerated() {
            guard i < now.count else { out.append("item \(i + 1): missing"); continue }
            let back = Dictionary(now[i].entries.map { ($0.type, $0.data) }, uniquingKeysWith: { a, _ in a })
            for entry in item.entries {
                guard let data = back[entry.type] else { out.append("item \(i + 1): \(entry.type): missing"); continue }
                if data != entry.data { out.append("item \(i + 1): \(entry.type): \(entry.data.count) bytes came back as \(data.count) different bytes") }
            }
        }
        if now.count > expected.count { out.append("\(now.count - expected.count) more item(s) than were saved") }
        return out
    }

    private let backend: PasteboardBackend
    private var saved: [PasteboardItemData]?
    /// What the last save found it could not restore. While non-empty, `writeOwn` writes nothing,
    /// so the pasteboard keeps the user's contents untouched.
    public private(set) var refused: [String] = []
    /// The types of each item the last save read, for the debug state: type names only, never data.
    /// Kept after the restore.
    public private(set) var savedTypes: [[String]]?
    /// The types the last save could not read, item by item ("item 2: public.file-url"): a restore
    /// cannot bring them back. Empty when every type was read.
    public private(set) var lost: [String] = []
    /// The change count Caret's own write produced.
    public private(set) var ownCount: Int?
    /// What the last restore read back differently from what it saved (`mismatches`). Empty after
    /// a restore that came back exactly, and when nothing was restored.
    public private(set) var mismatched: [String] = []

    public init(backend: PasteboardBackend) { self.backend = backend }

    public func save() {
        let items = backend.read()
        saved = items
        savedTypes = items.map { $0.types + $0.unreadable.map { "\($0) (unreadable)" } }
        lost = items.enumerated().flatMap { i, item in item.unreadable.map { "item \(i + 1): \($0)" } }
        refused = Self.unrestorable(items)
        ownCount = nil
    }

    /// What a restore of the pasteboard as it is now could not put back exactly. The executor asks
    /// this before choosing the paste route; `save` checks again on the items it actually keeps.
    public func unrestorableNow() -> [String] { Self.unrestorable(backend.read()) }

    /// Writes `text` as Caret's own item. Returns the change count it produced, or nil when the
    /// last save was refused: nothing is written, so a paste posted anyway pastes the user's own
    /// contents, never a partial restore's.
    @discardableResult
    public func writeOwn(_ text: String) -> Int? {
        guard refused.isEmpty else { return nil }
        var entries: [(type: String, data: Data)] = [(Self.plainText, Data(text.utf8))]
        for marker in Self.markerTypes { entries.append((marker, Data())) }
        // The clear's own count, never one read afterwards: a copy made between the write and a later
        // read would otherwise be taken for Caret's and overwritten by the restore (A17 review). Writing
        // the items does not move the count (GeneralPasteboardTests pins this).
        let count = backend.replace(with: [PasteboardItemData(entries)])
        ownCount = count
        return count
    }

    /// Puts the saved contents back if the pasteboard still holds Caret's write.
    public func restore() -> Outcome {
        defer {
            saved = nil
            ownCount = nil
            refused = []
        }
        mismatched = []
        guard let own = ownCount, let saved else { return .notWritten }
        guard backend.changeCount == own else { return .skippedUserCopied }
        let cleared = backend.replace(with: saved)
        guard cleared == own + 1 else { return .raced }
        // Restored by count; the bytes are checked too, since a count says nothing about what an
        // owner's pasteboard type gives back.
        mismatched = Self.mismatches(saved: saved, now: backend.read())
        return .restored
    }
}
