import Foundation

/// One pasteboard item: every type it carries, in the order the pasteboard listed them, with its data.
public struct PasteboardItemData: Equatable, Sendable {
    public var entries: [(type: String, data: Data)]
    /// Types the pasteboard listed for the item whose data could not be read, so a restore cannot
    /// bring them back. Reported, never guessed at.
    public var unreadable: [String]

    public init(_ entries: [(type: String, data: Data)], unreadable: [String] = []) {
        self.entries = entries
        self.unreadable = unreadable
    }

    public var types: [String] { entries.map { $0.type } }

    public static func == (a: Self, b: Self) -> Bool {
        a.unreadable == b.unreadable && a.entries.count == b.entries.count && zip(a.entries, b.entries).allSatisfy { $0.type == $1.type && $0.data == $1.data }
    }
}

/// The few pasteboard calls the reconcile needs, so it tests against a fake and runs against
/// `NSPasteboard` (`GeneralPasteboard` in CaretHost).
public protocol PasteboardBackend: AnyObject {
    var changeCount: Int { get }
    /// Every item, every type.
    func read() -> [PasteboardItemData]
    /// Clears the pasteboard and writes `items` (none leaves it empty). Returns the change count
    /// the clear produced, which a write by anyone else between the caller's check and this call
    /// would have moved past `expected + 1`.
    func replace(with items: [PasteboardItemData]) -> Int
}

/// Insertion through the general pasteboard, by Sam's decision of 2026-10-04: paste, then reconcile.
///
/// 1. `save` copies every item and type on the pasteboard, and its change count.
/// 2. `writeOwn` writes Caret's text marked with the nspasteboard.org transient, concealed and
///    auto-generated types, so clipboard managers skip it, and records the change count that write
///    produced: from then on, that count means "still Caret's".
/// 3. `restore`, once the paste has landed, puts the saved items back only if the count is still
///    Caret's. Any other count means someone wrote in between (the user copied), and their copy
///    stays. An empty saved pasteboard is restored as empty.
///
/// Known limit: NSPasteboard has no compare-and-swap, so a copy made in the instant between the
/// restore's count check and its clear (two adjacent calls on one thread) is overwritten. The clear's
/// own count shows that it happened (`Outcome.raced`), and the debug state reports it; nothing can
/// bring that copy back. Closing it would take not restoring at all.
public final class ReconcilingClipboard {
    public enum Outcome: String, Codable, Equatable, Sendable {
        /// The saved contents are back.
        case restored
        /// Someone wrote after Caret did; their contents stay and Caret's saved copy is dropped.
        case skippedUserCopied
        /// The check passed but another write landed before the clear: it was overwritten.
        case raced
        /// Nothing was written by Caret, so there was nothing to put back.
        case notWritten
    }

    /// nspasteboard.org's markers. A clipboard manager that honours them does not record the item.
    public static let markerTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    public static let plainText = "public.utf8-plain-text"

    /// Types Caret puts back byte for byte and the owning app reads back as the same thing: text,
    /// rich text, HTML and images, which are plain data with no reference to anything outside the
    /// bytes, plus the markers above.
    ///
    /// Everything else refuses the paste route for that insert (lead decision, 2026-10-04). A
    /// silent partial restore is worse than no paste. A17's VM probe (vm-insert run 1,
    /// clipboard/pasteboard.ndjson) put back an item holding `public.file-url` 5 of 5 times
    /// reported `restored` with nothing unreadable, and the item was gone each time. So "every
    /// type read" does not prove "every type restored". A private type round-tripped its bytes in
    /// that probe, but bytes do not show that its owner reads them back as the same thing (a file
    /// promise, a reference into the owner's memory). So an unknown type refuses too. This list
    /// is a judgment from the types' definitions. Only the text types and the probe's own private
    /// type were tested on a real pasteboard; the image types were not.
    public static let restorableTypes = Set([
        "public.utf8-plain-text", "public.utf16-plain-text", "public.utf16-external-plain-text", "public.plain-text",
        "public.rtf", "com.apple.flat-rtfd", "public.html",
        "public.png", "public.tiff",
    ] + markerTypes)

    /// What in `items` a restore could not put back exactly, item by item ("item 2: public.file-url"):
    /// types it could not read and types outside `restorableTypes`. Empty when the paste route may
    /// be used.
    public static func unrestorable(_ items: [PasteboardItemData]) -> [String] {
        items.enumerated().flatMap { i, item in
            (item.unreadable + item.types.filter { !restorableTypes.contains($0) }).map { "item \(i + 1): \($0)" }
        }
    }

    private let backend: PasteboardBackend
    private var saved: [PasteboardItemData]?
    /// What the last save found it could not restore. While non-empty, `writeOwn` writes nothing,
    /// so the pasteboard keeps the user's contents untouched.
    public private(set) var refused: [String] = []
    /// The types the last save could not read, item by item ("item 2: public.file-url"): a restore
    /// cannot bring them back. Empty when every type was read.
    public private(set) var lost: [String] = []
    /// The change count Caret's own write produced.
    public private(set) var ownCount: Int?

    public init(backend: PasteboardBackend) { self.backend = backend }

    public func save() {
        let items = backend.read()
        saved = items
        lost = items.enumerated().flatMap { i, item in item.unreadable.map { "item \(i + 1): \($0)" } }
        refused = Self.unrestorable(items)
        ownCount = nil
    }

    /// What a restore of the pasteboard as it is now could not put back exactly. The executor asks
    /// this before choosing the paste route; `save` checks again on the items it actually keeps.
    public func unrestorableNow() -> [String] { Self.unrestorable(backend.read()) }

    /// Writes `text` as Caret's own item. Returns the change count it produced, or nil when the
    /// last save was refused: nothing is written, so a paste posted anyway pastes the user's own
    /// contents, never a partial restore's.
    @discardableResult
    public func writeOwn(_ text: String) -> Int? {
        guard refused.isEmpty else { return nil }
        var entries: [(type: String, data: Data)] = [(Self.plainText, Data(text.utf8))]
        for marker in Self.markerTypes { entries.append((marker, Data())) }
        // The clear's own count, never one read afterwards: a copy made between the write and a later
        // read would otherwise be taken for Caret's and overwritten by the restore (A17 review). Writing
        // the items does not move the count (GeneralPasteboardTests pins this).
        let count = backend.replace(with: [PasteboardItemData(entries)])
        ownCount = count
        return count
    }

    /// Puts the saved contents back if the pasteboard still holds Caret's write.
    public func restore() -> Outcome {
        defer {
            saved = nil
            ownCount = nil
            refused = []
        }
        guard let own = ownCount, let saved else { return .notWritten }
        guard backend.changeCount == own else { return .skippedUserCopied }
        let cleared = backend.replace(with: saved)
        return cleared == own + 1 ? .restored : .raced
    }
}
