import XCTest
@testable import CaretHostCore

/// Paste, then reconcile (Sam's decision of 2026-10-04), against a pasteboard that counts changes the
/// way `NSPasteboard` does: each clear moves the count by one. `GeneralPasteboardTests` checks that
/// premise against a real, private named pasteboard.
final class ClipboardReconcileTests: XCTestCase {
    final class FakePasteboard: PasteboardBackend {
        var changeCount = 100
        var items: [PasteboardItemData] = []
        /// Runs inside `replace`, before the clear: someone else's write in that instant.
        var beforeClear: (() -> Void)?

        func read() -> [PasteboardItemData] { items }

        func replace(with items: [PasteboardItemData]) -> Int {
            beforeClear?()
            beforeClear = nil
            changeCount += 1
            self.items = items
            return changeCount
        }

        /// The user copies.
        func copy(_ item: PasteboardItemData) {
            changeCount += 1
            items = [item]
        }
    }

    private func item(_ pairs: [(String, String)]) -> PasteboardItemData {
        PasteboardItemData(pairs.map { (type: $0.0, data: Data($0.1.utf8)) })
    }

    private let rich = PasteboardItemData([
        ("public.rtf", Data("{\\rtf1 Hello}".utf8)),
        ("public.html", Data("<b>Hello</b>".utf8)),
        ("public.utf8-plain-text", Data("Hello".utf8)),
    ])

    func testCaretsItemIsMarkedSoClipboardManagersSkipIt() {
        let pb = FakePasteboard()
        let clipboard = ReconcilingClipboard(backend: pb)
        clipboard.save()
        let own = clipboard.writeOwn("Lumen Labs")
        XCTAssertEqual(own, pb.changeCount)
        XCTAssertEqual(pb.items.count, 1)
        XCTAssertEqual(pb.items[0].types, ["public.utf8-plain-text", "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType"])
        XCTAssertEqual(pb.items[0].entries[0].data, Data("Lumen Labs".utf8))
    }

    func testEveryTypeOfEveryPriorItemComesBack() {
        let pb = FakePasteboard()
        let second = PasteboardItemData([("public.png", Data([0x89, 0x50, 0x4E, 0x47])), ("public.utf8-plain-text", Data("a.png".utf8))])
        pb.items = [rich, second]
        let clipboard = ReconcilingClipboard(backend: pb)
        clipboard.save()
        XCTAssertNotNil(clipboard.writeOwn("Lumen Labs"))
        XCTAssertEqual(clipboard.restore(), .restored)
        XCTAssertEqual(pb.items, [rich, second], "rich text, HTML, an image and a second item, in order")
    }

    /// The lead's refusal rule (2026-10-04): a file URL (lost 5 of 5 in A17's VM probe while the
    /// restore said `restored`) and a private type no one has shown Caret can restore both refuse
    /// the paste route. The save writes nothing, so the user's clipboard is never touched.
    func testAFileURLAndAnUnknownPrivateTypeRefuseThePaste() {
        let pb = FakePasteboard()
        let files = item([("public.file-url", "file:///tmp/a.txt"), ("public.utf8-plain-text", "a.txt")])
        let app = item([("com.example.private", "\u{0}\u{1}"), ("public.utf8-plain-text", "Hello")])
        pb.items = [files, app]
        let clipboard = ReconcilingClipboard(backend: pb)
        XCTAssertEqual(clipboard.unrestorableNow(), ["item 1: public.file-url", "item 2: com.example.private"])
        XCTAssertEqual(WriteFallback.firstRoute(appPastes: true, clipboardRestorable: false), .axWrite, "an app that pastes gets the AX write instead")
        XCTAssertEqual(WriteFallback.afterAXRefused(clipboardRestorable: false), .failed(WriteFallback.clipboardUnrestorable), "and no paste if that is refused")

        let count = pb.changeCount
        clipboard.save()
        XCTAssertEqual(clipboard.refused, ["item 1: public.file-url", "item 2: com.example.private"])
        XCTAssertNil(clipboard.writeOwn("Lumen Labs"))
        XCTAssertEqual(pb.changeCount, count, "nothing written")
        XCTAssertEqual(pb.items, [files, app])
        XCTAssertEqual(clipboard.restore(), .notWritten)
        XCTAssertEqual(pb.items, [files, app])
        XCTAssertEqual(clipboard.refused, [], "the next save decides afresh")

        for one in [files, app] {
            pb.items = [rich, one]
            XCTAssertEqual(clipboard.unrestorableNow().count, 1, "either alone refuses")
        }
    }

    func testTextRichTextHTMLImagesAndCaretsMarkersMayBePasted() {
        let pb = FakePasteboard()
        let types = ["public.utf8-plain-text", "public.utf16-external-plain-text", "public.rtf", "com.apple.flat-rtfd", "public.html", "public.png", "public.tiff"]
            + ReconcilingClipboard.markerTypes
        pb.items = [PasteboardItemData(types.map { (type: $0, data: Data("x".utf8)) })]
        let clipboard = ReconcilingClipboard(backend: pb)
        XCTAssertEqual(clipboard.unrestorableNow(), [])
        XCTAssertEqual(WriteFallback.firstRoute(appPastes: true, clipboardRestorable: true), .paste)
        XCTAssertEqual(WriteFallback.firstRoute(appPastes: false, clipboardRestorable: true), .axWrite, "the AX write stays first")
        XCTAssertEqual(WriteFallback.afterAXRefused(clipboardRestorable: true), .fallBackToPaste)
        pb.items = []
        XCTAssertEqual(clipboard.unrestorableNow(), [], "an empty clipboard is restored as empty")
    }

    func testAnEmptyPasteboardIsLeftEmpty() {
        let pb = FakePasteboard()
        let clipboard = ReconcilingClipboard(backend: pb)
        clipboard.save()
        clipboard.writeOwn("Lumen Labs")
        XCTAssertEqual(clipboard.restore(), .restored)
        XCTAssertEqual(pb.items, [], "Caret's text does not stay behind")
    }

    /// The user copies between Caret's write and the restore: their copy stays, and Caret's saved
    /// copy of the older contents is dropped.
    func testACopyMadeDuringThePasteIsNeverOverwritten() {
        let pb = FakePasteboard()
        pb.items = [rich]
        let clipboard = ReconcilingClipboard(backend: pb)
        clipboard.save()
        clipboard.writeOwn("Lumen Labs")
        let theirs = item([("public.utf8-plain-text", "copied mid-paste")])
        pb.copy(theirs)
        let count = pb.changeCount
        XCTAssertEqual(clipboard.restore(), .skippedUserCopied)
        XCTAssertEqual(pb.items, [theirs])
        XCTAssertEqual(pb.changeCount, count, "nothing was written after their copy")
        XCTAssertEqual(clipboard.restore(), .notWritten, "a second restore has nothing to do")
    }

    func testACopyInTheInstantBeforeTheClearIsReportedAsARace() {
        let pb = FakePasteboard()
        pb.items = [rich]
        let clipboard = ReconcilingClipboard(backend: pb)
        clipboard.save()
        clipboard.writeOwn("Lumen Labs")
        pb.beforeClear = { pb.copy(self.item([("public.utf8-plain-text", "too late")])) }
        XCTAssertEqual(clipboard.restore(), .raced, "the debug state says so; nothing can bring it back")
    }

    /// A type the pasteboard lists but will not give data for cannot be restored: the save says
    /// which, for the debug state, and refuses rather than restoring less and calling it whole.
    func testATypeThatCannotBeReadIsReportedAndRefused() {
        let pb = FakePasteboard()
        pb.items = [rich, PasteboardItemData([], unreadable: ["public.utf8-plain-text"])]
        let clipboard = ReconcilingClipboard(backend: pb)
        clipboard.save()
        XCTAssertEqual(clipboard.lost, ["item 2: public.utf8-plain-text"])
        XCTAssertEqual(clipboard.refused, ["item 2: public.utf8-plain-text"], "even a type that is otherwise restorable")
        XCTAssertNil(clipboard.writeOwn("Lumen Labs"))
        XCTAssertEqual(clipboard.restore(), .notWritten)
        XCTAssertEqual(pb.items.first, rich)
    }

    func testNothingIsRestoredWhenCaretNeverWrote() {
        let pb = FakePasteboard()
        pb.items = [rich]
        let clipboard = ReconcilingClipboard(backend: pb)
        clipboard.save()
        let count = pb.changeCount
        XCTAssertEqual(clipboard.restore(), .notWritten)
        XCTAssertEqual(pb.changeCount, count)
        XCTAssertEqual(pb.items, [rich])
    }
}

/// The host's live write authorization (S1 audit #2).
final class HostAuthorityTests: XCTestCase {
    func testARevokeEndsEveryEarlierGrantAndNoLaterOne() {
        let authority = HostAuthority()
        let a = authority.grant()
        let b = authority.grant()
        XCTAssertTrue(authority.isLive(a))
        XCTAssertTrue(authority.isLive(b))
        authority.revokeAll("stop")
        XCTAssertFalse(authority.isLive(a))
        XCTAssertFalse(authority.isLive(b))
        let c = authority.grant()
        XCTAssertTrue(authority.isLive(c), "a Tab after the stop is a new decision")
        authority.revokeAll("helperDisconnected")
        XCTAssertFalse(authority.isLive(c))
        XCTAssertEqual(authority.debugInfo.revokes, 2)
        XCTAssertEqual(authority.debugInfo.lastReason, "helperDisconnected")
    }

    /// A revoke from another thread is seen by the next check on the insertion queue.
    func testARevokeFromAnotherThreadIsSeenAtTheNextCheck() {
        let authority = HostAuthority()
        let grant = authority.grant()
        let revoked = expectation(description: "revoked")
        DispatchQueue.global().async {
            authority.revokeAll("paused")
            revoked.fulfill()
        }
        wait(for: [revoked], timeout: 2)
        XCTAssertFalse(authority.isLive(grant))
    }
}
