// Every instruction the five B28 reviews used to get past the scope words, with the form's title where the review set
// one. None may be a whole form or a section that stands without Jev: test/scope-words.test.ts checks the grammar
// alone, test/ask.test.ts checks planAsk with a Jev that confirms nothing.
export const REVIEWED: readonly [string, string?][] = [
  // Review 5: quote characters the quote rule missed, a restriction inside the form's title, and a period before "in"
  // that let "in my email" be read as where to copy from.
  ["fill in ＂everything＂"],
  ["fill in 〝everything〞"],
  ["fill out the email only", "Email only"],
  ["fill out the email and not phone", "Email and not phone"],
  ["fill.in my email on this form"],
  // The same period beside a section phrase.
  ["fill.in my email, my contact info"],
  ["do my contact info.in my email only"],
  // Reviews 1-4.
  ["just fill my email on this form"],
  ["put everything from my note in Notes"],
  ["fill the rest of the address"],
  ["do the rest of the address"],
  ["only the rest of the address"],
  ["Write ‘everything’ in Notes"],
  ["Write 'fill in everything' in Notes"],
  ["my email from the 'everything' note"],
  ['fill "Email" on this form'],
  ["fill in everything, the phone is (512) 555-0147"],
  ["skip my contact info, do the rest"],
  ["avoid my contact info, do the rest"],
  ["my contact info, but not the phone"],
  ["only my email in contact info"],
  ["only the second box in contact info"],
  ["fill only part of my contact info"],
  ["fill a bit of my details"],
  ["do everything from my note except email"],
  ["do everything in my details except email"],
  ["put that in this form"],
  ["do it on this form"],
  ["fill out the email only", "Email signup | Members only"],
  ["fill in Bea's linkedin on this form"],
  ["fill in what I typed on this form"],
  ["fill only Bea's linkedin in my contact info"],
  ["fill only what I wrote in contact info"],
  ["do the whole form but `phone`"],
  ["fill in everything «Email»"],
  ["fill in only the `contact info`"],
  ["fill in only the «contact info»"],
  ["fill in only the „contact info“"],
  ['only my "Email" in contact info'],
  ["everything but the phone"],
  ["fill out everything except LinkedIn"],
  ["don't do the whole form"],
  ["just my email, leave the rest"],
  ["my email and phone, leave the rest"],
  ["Fill only Email; do not change Phone"],
];
