// Execute the production gate against isolated source/config changes, never the app build.
import { afterEach, describe, expect, it } from "vitest";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = fileURLToPath(new URL("../../", import.meta.url));
const fixtures: string[] = [];
afterEach(() => { for (const path of fixtures.splice(0)) rmSync(path, { recursive: true, force: true }); });
function fixture(): string {
  const path = mkdtempSync(join(tmpdir(), "caret-gate-"));
  fixtures.push(path);
  for (const dir of ["helper/src", "helper/scripts", "scripts", "caret", "apps/mac/Sources/Caret"]) mkdirSync(join(path, dir), { recursive: true });
  cpSync(join(root, "helper/src"), join(path, "helper/src"), { recursive: true });
  for (const file of ["helper/scripts/privacy-gate.ts", "scripts/check_vercel_gemini.py", "scripts/check_onboarding_privacy.py", "apps/mac/Sources/Caret/PermissionView.swift", "caret/completions.py", "apps/mac/Sources/Caret/Info.plist", ...SWIFT]) {
    mkdirSync(dirname(join(path, file)), { recursive: true });
    cpSync(join(root, file), join(path, file));
  }
  return path;
}
const VIEW = "apps/caret/Sources/CaretHost/Onboarding/OnboardingView.swift";
const SWIFT = [VIEW];
/** An assembled app's resource holding the approved bytes, generated by the gate as build-app.sh does. */
function shippedResource(path: string): string {
  const shipped = join(path, "Caret.app/Contents/Resources/PrivacyPromise.txt");
  mkdirSync(join(path, "Caret.app/Contents"), { recursive: true });
  writeFileSync(join(path, "Caret.app/Contents/Info.plist"), '<?xml version="1.0" encoding="UTF-8"?>\n<plist version="1.0"><dict/></plist>\n');
  expect(gate(path, "0", { CARET_PRIVACY_RESOURCE: shipped }).status).toBe(0);
  return shipped;
}
function acceptAll(path: string): void {
  mkdirSync(join(path, "helper/src/privacy"), { recursive: true });
  writeFileSync(join(path, "helper/src/privacy/accepted.ts"), 'export const PRIVACY_ACCEPTANCES = { "pv2-sites-send": { commit: "0123456789abcdef0123456789abcdef01234567", by: "fixture reviewer", at: "2026-10-07T00:00:00Z" }, "ha2-copied-conversation": { commit: "0123456789abcdef0123456789abcdef01234567", by: "fixture reviewer", at: "2026-10-07T00:00:00Z" } };\n');
}
function gate(path: string, enabled = "0", extra: Record<string, string> = {}) {
  return spawnSync(process.execPath, [join(path, "helper/scripts/privacy-gate.ts")], {
    encoding: "utf8", env: { ...process.env, CARET_DEV_VERCEL_GEMINI: enabled, CARET_PRIVACY_RESOURCE: join(path, "PrivacyPromise.txt"), ...extra },
  });
}
/** The finished-app check alone, as build-app.sh, the Xcode phase and package_mac.py run it once the app is assembled. */
function verify(path: string, shipped: string, extra: Record<string, string> = {}) {
  const env: Record<string, string | undefined> = { ...process.env, CARET_DEV_VERCEL_GEMINI: "0", CARET_VERIFY_PRIVACY_RESOURCE: shipped, ...extra };
  if (!("CARET_PRIVACY_RESOURCE" in extra)) delete env.CARET_PRIVACY_RESOURCE;
  return spawnSync(process.execPath, [join(path, "helper/scripts/privacy-gate.ts")], { encoding: "utf8", env });
}

describe("privacy build gate", () => {
  it("refuses PV2 independently of the owner-note disclosure", () => {
    const path = fixture(); acceptAll(path);
    const file = join(path, "helper/src/privacy/accepted.ts");
    writeFileSync(file, readFileSync(file, "utf8").replace(/"pv2-sites-send": \{[^}]*\}/, '"pv2-sites-send": null'));
    const result = gate(path);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("PV2's Sites and send-boundary fixes aren't accepted yet; the promise's switched-off sentence isn't backed");
    expect(result.stderr).not.toContain("OWNER_NOTE_DISCLOSURE");
  });
  it("refuses the copied-conversation condition independently of PV2", () => {
    const path = fixture(); acceptAll(path);
    const file = join(path, "helper/src/privacy/accepted.ts");
    writeFileSync(file, readFileSync(file, "utf8").replace(/"ha2-copied-conversation": \{[^}]*\}/, '"ha2-copied-conversation": null'));
    const result = gate(path);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("ha2-copied-conversation");
    expect(result.stderr).toContain("No request carries more than half of a conversation.");
    expect(result.stderr).not.toContain("pv2-sites-send");
  });
  it("refuses the owner-note disclosure independently of PV2", () => {
    const path = fixture(); acceptAll(path);
    const file = join(path, "helper/src/privacy.ts");
    // TODO(INT1): the allotment is 0 until re-expressed on the output-based ledger, and at 0 no disclosure is needed;
    // the gate is checked at the 2,000 Sam approved.
    writeFileSync(file, readFileSync(file, "utf8").replace(/export const OWNER_NOTE_DISCLOSURE: string \| null = "[^"\n]*";/, "export const OWNER_NOTE_DISCLOSURE: string | null = null;").replace("export const OWNER_NOTE_CHARS = 0;", "export const OWNER_NOTE_CHARS = 2000;"));
    expect(readFileSync(file, "utf8")).toContain("export const OWNER_NOTE_CHARS = 2000;");
    expect(gate(path).stderr).toContain("OWNER_NOTE_DISCLOSURE");
    expect(gate(path).status).toBe(1);
  });
  it("allows an accepted, disclosed tree with Gemini off", () => {
    const path = fixture(); acceptAll(path);
    expect(gate(path).status).toBe(0);
    const source = readFileSync(join(path, "helper/src/privacy.ts"), "utf8");
    expect(readFileSync(join(path, "PrivacyPromise.txt"), "utf8")).toBe(source.split("export const PRIVACY_PROMISE = `")[1]?.split("`;")[0]);
  });
  it("refuses an assembled app whose promise is missing, empty or different", () => {
    const path = fixture(); acceptAll(path);
    const shipped = shippedResource(path);
    expect(verify(path, shipped).status).toBe(0);
    const cases: [string, () => void, string][] = [
      ["missing", () => rmSync(shipped), "is missing"],
      ["empty", () => writeFileSync(shipped, ""), "is empty"],
      ["whitespace", () => writeFileSync(shipped, "\n\n"), "is empty"],
      ["different", () => writeFileSync(shipped, "What Caret sends\n\nA sentence nobody approved."), "differs from PRIVACY_PROMISE"],
    ];
    for (const [, damage, why] of cases) {
      damage();
      const result = verify(path, shipped);
      expect(result.status).toBe(1);
      expect(result.stderr).toContain(`privacy gate: refusing to package: the app's privacy promise ${shipped} ${why}`);
    }
  });
  it("refuses an onboarding view that shows other words than the resource", () => {
    for (const [original, edit] of [
      ["return PrivacyPromise(text)", "return nil"],
      ["var promise = PermissionsScreen.privacyLine\n", 'var promise = PermissionsScreen.privacyLine ?? PrivacyPromise("")\n'],
      ["Text(text)\n", 'Text("It sends nothing from an app or website you\'ve switched off.")\n'],
    ] as const) {
      const path = fixture(); acceptAll(path);
      const view = readFileSync(join(path, VIEW), "utf8");
      expect(view.split(original).length).toBe(2);
      writeFileSync(join(path, VIEW), view.replace(original, edit));
      const result = gate(path);
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("the onboarding copy must render PRIVACY_PROMISE");
    }
  });
  it("refuses a promise that is a symbolic link or lies outside the app", () => {
    const path = fixture(); acceptAll(path);
    const shipped = shippedResource(path);
    const outside = join(path, "approved-elsewhere.txt");
    cpSync(shipped, outside);
    rmSync(shipped);
    symlinkSync(outside, shipped);
    expect(verify(path, shipped).stderr).toContain("is a symbolic link");
    expect(verify(path, shipped).status).toBe(1);
    // Resources itself pointing out of the app: the file is regular, but not inside the bundle.
    const resources = dirname(shipped);
    rmSync(resources, { recursive: true });
    mkdirSync(join(path, "elsewhere"));
    cpSync(outside, join(path, "elsewhere/PrivacyPromise.txt"));
    symlinkSync(join(path, "elsewhere"), resources);
    expect(verify(path, shipped).stderr).toContain("is outside");
    expect(verify(path, shipped).status).toBe(1);
    // A path that is not in an app bundle at all.
    expect(verify(path, outside).stderr).toContain("is not at <name>.app/Contents/Resources/PrivacyPromise.txt");
    expect(verify(path, outside).status).toBe(1);
  });
  it("never writes the promise during a verification run", () => {
    const path = fixture(); acceptAll(path);
    const shipped = shippedResource(path);
    for (const damage of [() => rmSync(shipped), () => writeFileSync(shipped, "A sentence nobody approved.")]) {
      damage();
      const before = existsSync(shipped) ? readFileSync(shipped, "utf8") : null;
      const result = verify(path, shipped, { CARET_PRIVACY_RESOURCE: shipped });
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("CARET_PRIVACY_RESOURCE");
      expect(existsSync(shipped) ? readFileSync(shipped, "utf8") : null).toBe(before);
    }
  });
  it("refuses a Gemini default changed to on", () => {
    const path = fixture(); acceptAll(path);
    const file = join(path, "caret/completions.py");
    writeFileSync(file, readFileSync(file, "utf8").replace("VERCEL_GEMINI_ENABLED = False", "VERCEL_GEMINI_ENABLED = True"));
    const result = gate(path);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("VERCEL_GEMINI_ENABLED must default to False");
  });
  it("refuses an enabled build environment", () => {
    const path = fixture(); acceptAll(path);
    const result = gate(path, "1");
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("CARET_DEV_VERCEL_GEMINI=1");
  });
  it("refuses a packaged launch environment enabling Gemini", () => {
    const path = fixture(); acceptAll(path);
    writeFileSync(join(path, "apps/mac/Sources/Caret/Info.plist"), '<?xml version="1.0"?><plist version="1.0"><dict><key>LSEnvironment</key><dict><key>CARET_DEV_VERCEL_GEMINI</key><string>1</string></dict></dict></plist>');
    const result = gate(path);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("LSEnvironment");
  });
});
